version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    versioning-strategy: increase
    reviewers:
      - coliff
    labels:
      - dependencies
    open-pull-requests-limit: 1
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    reviewers:
      - coliff
